const mongoose = require('mongoose');
const Car = require('./models/Car');
const User = require('./models/User');
require('dotenv').config();

const cars = [
    // ============ HATCHBACKS ============
    {
        name: 'Alto K10',
        brand: 'Maruti Suzuki',
        year: 2024,
        description: 'India\'s most loved entry-level hatchback. Powered by a 1.0L K10C DualJet engine producing 67 PS, the Alto K10 offers an impressive 24.39 km/l mileage. Features 6 airbags, ABS with EBD, and an optional AGS automatic transmission. Perfect for city commutes with its compact 3530mm length and 4.5m turning radius.',
        images: ['/cars/alto-k10.png'],
        seats: 4,
        fuelType: 'Petrol',
        transmission: 'Manual',
        pricePerHour: 60,
        pricePerDay: 600,
        available: true,
        features: ['AC', 'Power Steering', 'Central Locking', 'Front Airbags'],
        rules: 'No smoking. Return with same fuel level. Speed limit 80 km/h.',
        rating: 4.1,
        totalBookings: 72,
        category: 'Hatchback',
    },
    {
        name: 'Baleno',
        brand: 'Maruti Suzuki',
        year: 2024,
        description: 'Nexa\'s premium hatchback with a bold design and SmartPlay Pro+ infotainment. The Baleno packs a 1.2L DualJet engine with 90 PS, delivering 22.35 km/l. Features include a 9-inch HD SmartPlay Pro+ touchscreen, 360-degree camera, heads-up display, and 6 airbags. A coupe-like silhouette makes it stand out in the premium hatchback segment.',
        images: ['/cars/baleno.png'],
        seats: 5,
        fuelType: 'Petrol',
        transmission: 'Manual',
        pricePerHour: 100,
        pricePerDay: 1000,
        available: true,
        features: ['AC', 'Touchscreen Infotainment', 'Bluetooth', 'Cruise Control', 'Rear Camera', 'LED DRLs'],
        rules: 'No smoking. Return with same fuel level. Report any damage immediately.',
        rating: 4.4,
        totalBookings: 58,
        category: 'Hatchback',
    },
    {
        name: 'i20',
        brand: 'Hyundai',
        year: 2024,
        description: 'The sporty premium hatchback from Hyundai with segment-first features. Powered by a 1.2L Kappa engine (88 PS) or a 1.0L Turbo GDi (120 PS). Boasts a 10.25-inch touchscreen, Bose premium audio, sunroof, wireless charging, and BlueLink connected car technology. The parametric jewel-pattern grille and Z-shaped LED tail lamps define its bold design.',
        images: ['/cars/i20.png'],
        seats: 5,
        fuelType: 'Petrol',
        transmission: 'Manual',
        pricePerHour: 110,
        pricePerDay: 1100,
        available: true,
        features: ['AC', 'Sunroof', 'Wireless Charging', 'Bose Speakers', 'LED Headlamps', 'Cruise Control'],
        rules: 'No smoking. Return with same fuel level. Report any damage immediately.',
        rating: 4.5,
        totalBookings: 65,
        category: 'Hatchback',
    },
    {
        name: 'Fronx',
        brand: 'Maruti Suzuki',
        year: 2024,
        description: 'Nexa\'s stylish coupe-SUV crossover with a floating roof design. Available with a 1.0L BoosterJet turbo engine (100 PS) or 1.2L DualJet. Features include a heads-up display, wireless charging, 360-degree camera, and Suzuki Connect. Its bold design with contrast roof and sporty LED lighting makes it a head-turner.',
        images: ['/cars/fronx.png'],
        seats: 5,
        fuelType: 'Petrol',
        transmission: 'Automatic',
        pricePerHour: 120,
        pricePerDay: 1200,
        available: true,
        features: ['AC', 'HUD Display', 'Wireless Charging', '360 Camera', 'Cruise Control', 'Connected Car'],
        rules: 'No smoking. Return with same fuel level. Report any damage immediately.',
        rating: 4.5,
        totalBookings: 42,
        category: 'Hatchback',
    },
    {
        name: 'Polo',
        brand: 'Volkswagen',
        year: 2022,
        description: 'The legendary German-engineered hatchback that set benchmarks in India. Powered by a refined 1.0L TSI turbo-petrol producing 110 PS and 175 Nm. Known for its rock-solid build quality, precise steering, and fun-to-drive character. Though discontinued, the Polo remains a cult classic among driving enthusiasts with its European DNA and timeless design.',
        images: ['/cars/polo.png'],
        seats: 5,
        fuelType: 'Petrol',
        transmission: 'Manual',
        pricePerHour: 90,
        pricePerDay: 900,
        available: true,
        features: ['AC', 'ABS', 'Dual Airbags', 'Bluetooth', 'Power Windows'],
        rules: 'No smoking. Return with same fuel level. Report any damage immediately.',
        rating: 4.2,
        totalBookings: 55,
        category: 'Hatchback',
    },

    // ============ SEDANS ============
    {
        name: 'Swift Dzire',
        brand: 'Maruti Suzuki',
        year: 2024,
        description: 'India\'s best-selling compact sedan, now in its all-new 4th generation. Features a 1.2L Z-Series engine with 82 PS and segment-best 24.79 km/l mileage. Highlights include a 9-inch touchscreen, wireless CarPlay/Android Auto, 6 airbags, ESP, and a spacious 382L boot. The new design with sleek LED headlamps and alloy wheels gives it a premium appeal.',
        images: ['/cars/swift-dzire.png'],
        seats: 5,
        fuelType: 'Petrol',
        transmission: 'Manual',
        pricePerHour: 100,
        pricePerDay: 1000,
        available: true,
        features: ['AC', 'Bluetooth', 'Power Steering', 'USB Charging', 'Rear Camera'],
        rules: 'No smoking. Return with same fuel level. Speed limit 100 km/h.',
        rating: 4.3,
        totalBookings: 80,
        category: 'Sedan',
    },
    {
        name: 'Verna',
        brand: 'Hyundai',
        year: 2024,
        description: 'The 6th-generation Hyundai Verna with a 5-star Global NCAP safety rating. Choose between a 1.5L NA (113 PS) or 1.5L Turbo GDi (160 PS) with a 7-speed DCT. Loaded with ADAS Level 2, ventilated seats, Bose audio, 64-color ambient lighting, and a 10.25-inch digital cluster. The bold design with connected DRLs and parametric grille makes it a stunner.',
        images: ['/cars/verna.png'],
        seats: 5,
        fuelType: 'Petrol',
        transmission: 'Automatic',
        pricePerHour: 160,
        pricePerDay: 1600,
        available: true,
        features: ['AC', 'Sunroof', 'Ventilated Seats', 'ADAS', 'Wireless Charging', 'Bose Audio', 'Connected Car'],
        rules: 'No smoking. Return with same fuel level. Report any damage immediately.',
        rating: 4.7,
        totalBookings: 48,
        category: 'Sedan',
    },
    {
        name: 'City',
        brand: 'Honda',
        year: 2024,
        description: 'Honda\'s iconic mid-size sedan known for its bulletproof reliability and refined driving experience. Powered by a 1.5L i-VTEC engine (121 PS) paired with a CVT automatic. Features Honda SENSING ADAS, LaneWatch camera, Honda Connect app, wireless CarPlay, and LED headlamps. The City offers a premium cabin with excellent rear-seat comfort and a massive 506L boot.',
        images: ['/cars/honda-city.png'],
        seats: 5,
        fuelType: 'Petrol',
        transmission: 'Automatic',
        pricePerHour: 150,
        pricePerDay: 1500,
        available: true,
        features: ['AC', 'Sunroof', 'Lane Watch Camera', 'Honda Connect', 'LED Headlamps', 'Cruise Control'],
        rules: 'No smoking. Return with same fuel level. Report any damage immediately.',
        rating: 4.6,
        totalBookings: 36,
        category: 'Sedan',
    },
    {
        name: 'Ciaz',
        brand: 'Maruti Suzuki',
        year: 2022,
        description: 'A spacious and fuel-efficient mid-size sedan from Nexa. The Ciaz features a 1.5L K15B Smart Hybrid petrol engine (105 PS) with SHVS mild-hybrid technology for exceptional 20.65 km/l mileage. Highlights include SmartPlay infotainment, auto climate control, cruise control, and rear AC vents. Its elegant design and spacious 510L boot make it ideal for family travel.',
        images: ['/cars/ciaz.png'],
        seats: 5,
        fuelType: 'Petrol',
        transmission: 'Manual',
        pricePerHour: 110,
        pricePerDay: 1100,
        available: true,
        features: ['AC', 'SmartPlay Infotainment', 'Cruise Control', 'Auto Climate Control', 'Rear AC Vents'],
        rules: 'No smoking. Return with same fuel level. Report any damage immediately.',
        rating: 4.2,
        totalBookings: 30,
        category: 'Sedan',
    },

    // ============ SUVs ============
    {
        name: 'Creta',
        brand: 'Hyundai',
        year: 2024,
        description: 'India\'s best-selling SUV, now in its 2nd generation with bold parametric design. Available with 1.5L NA petrol (115 PS), 1.5L diesel (116 PS), or 1.5L Turbo GDi (160 PS). Features ADAS Level 2, panoramic sunroof, ventilated seats, Bose premium audio, 360-degree camera, and BlueLink connected car. The flagship SUV in the compact segment.',
        images: ['/cars/creta.png'],
        seats: 5,
        fuelType: 'Diesel',
        transmission: 'Automatic',
        pricePerHour: 180,
        pricePerDay: 1800,
        available: true,
        features: ['AC', 'Panoramic Sunroof', 'Ventilated Seats', 'ADAS', 'Wireless Charging', '360 Camera', 'Bose Audio'],
        rules: 'No smoking. Return with same fuel level. Report any damage immediately.',
        rating: 4.7,
        totalBookings: 70,
        category: 'SUV',
    },
    {
        name: 'Seltos',
        brand: 'Kia',
        year: 2024,
        description: 'Kia\'s feature-loaded compact SUV with segment-first technologies. Choose from 1.5L NA petrol, 1.5L diesel, or 1.5L Turbo GDi (160 PS) with a 7-speed DCT. Packed with ADAS, ventilated seats, Bose surround sound, panoramic sunroof, 360-degree camera, and Kia Connect. The tiger-nose grille and bold star-map LED DRLs make it instantly recognizable.',
        images: ['/cars/seltos.png'],
        seats: 5,
        fuelType: 'Petrol',
        transmission: 'Automatic',
        pricePerHour: 170,
        pricePerDay: 1700,
        available: true,
        features: ['AC', 'Ventilated Seats', 'Bose Audio', 'Sunroof', 'Connected Car', 'ADAS', '360 Camera'],
        rules: 'No smoking. Return with same fuel level. Report any damage immediately.',
        rating: 4.6,
        totalBookings: 52,
        category: 'SUV',
    },
    {
        name: 'Nexon',
        brand: 'Tata',
        year: 2024,
        description: 'India\'s first 5-star Global NCAP rated car in its segment. The Nexon features a 1.2L Turbo Revotron engine (120 PS) and an available EV variant. Highlights include a 10.25-inch floating touchscreen, Harman audio, ventilated seats, air purifier, and iRA connected car tech. The dual-tone design with coupe-like roofline is bold and distinctive.',
        images: ['/cars/nexon.png'],
        seats: 5,
        fuelType: 'Petrol',
        transmission: 'Manual',
        pricePerHour: 130,
        pricePerDay: 1300,
        available: true,
        features: ['AC', 'Sunroof', 'Harman Audio', 'Ventilated Seats', 'Air Purifier', 'Connected Car'],
        rules: 'No smoking. Return with same fuel level. 5-star NCAP safety rated.',
        rating: 4.5,
        totalBookings: 44,
        category: 'SUV',
    },
    {
        name: 'Brezza',
        brand: 'Maruti Suzuki',
        year: 2024,
        description: 'The all-new Brezza — bold, stylish, and loaded with tech. Powered by a 1.5L K15C DualJet engine (103 PS) with mild-hybrid tech delivering 20.15 km/l. Features include HUD display, wireless charging, 360-degree camera, electric sunroof, Suzuki Connect, and 6 airbags. The aggressive design with muscular wheel arches and dual-tone roof commands attention.',
        images: ['/cars/brezza.png'],
        seats: 5,
        fuelType: 'Petrol',
        transmission: 'Automatic',
        pricePerHour: 140,
        pricePerDay: 1400,
        available: true,
        features: ['AC', 'HUD Display', 'Wireless Charging', '360 Camera', 'Suzuki Connect', 'Electric Sunroof'],
        rules: 'No smoking. Return with same fuel level. Report any damage immediately.',
        rating: 4.4,
        totalBookings: 38,
        category: 'SUV',
    },
    {
        name: 'Scorpio N',
        brand: 'Mahindra',
        year: 2024,
        description: 'The Big Daddy of SUVs — reborn with a new platform and modern tech. Choose from a 2.0L mStallion turbo-petrol (200 PS) or 2.2L mHawk diesel (175 PS), both available with 4x4. Features include AdrenoX connected car, Sony 3D surround sound, dual-zone climate, sunroof, and terrain response modes. Built for those who command the road.',
        images: ['/cars/scorpio-n.png'],
        seats: 7,
        fuelType: 'Diesel',
        transmission: 'Automatic',
        pricePerHour: 200,
        pricePerDay: 2000,
        available: true,
        features: ['AC', '4x4', 'AdrenoX', 'Sony Audio', 'Dual Zone Climate', 'Sunroof', 'Terrain Modes'],
        rules: 'No off-roading without prior approval. No smoking. Return with same fuel level.',
        rating: 4.6,
        totalBookings: 35,
        category: 'SUV',
    },
    {
        name: 'Thar',
        brand: 'Mahindra',
        year: 2024,
        description: 'India\'s iconic off-roader with true 4x4 capability. Available with a 2.0L mStallion turbo-petrol (152 PS) or 2.2L mHawk diesel (132 PS), both with shift-on-fly 4WD. Features include a convertible roof, 10.25-inch touchscreen, cruise control, and adventure-ready build with 226mm ground clearance. The Thar is built for those who live for the thrill.',
        images: ['/cars/thar.png'],
        seats: 4,
        fuelType: 'Diesel',
        transmission: 'Manual',
        pricePerHour: 220,
        pricePerDay: 2200,
        available: true,
        features: ['AC', '4x4', 'Convertible Roof', 'Touchscreen', 'Cruise Control', 'Adventure Ready'],
        rules: 'Off-road permitted on designated trails only. No smoking. Return clean.',
        rating: 4.8,
        totalBookings: 60,
        category: 'SUV',
    },
    {
        name: 'XUV700',
        brand: 'Mahindra',
        year: 2024,
        description: 'Mahindra\'s flagship SUV with segment-first ADAS and premium features. Powered by a 2.0L mStallion turbo-petrol (200 PS) or 2.2L mHawk diesel (185 PS) with optional AWD. Features include ADAS Level 1, panoramic sunroof, Sony 3D surround sound, flush door handles, AdrenoX with Alexa, and a massive 10.25-inch dual-screen setup. The XUV700 is where technology meets adventure.',
        images: ['/cars/xuv700.png'],
        seats: 7,
        fuelType: 'Diesel',
        transmission: 'Automatic',
        pricePerHour: 250,
        pricePerDay: 2500,
        available: true,
        features: ['AC', 'ADAS', 'Panoramic Sunroof', 'Sony 3D Audio', 'Flush Door Handles', 'AdrenoX', 'Alexa'],
        rules: 'No smoking. Return with same fuel level. Report any damage immediately.',
        rating: 4.7,
        totalBookings: 28,
        category: 'SUV',
    },

    // ============ PREMIUM ============
    {
        name: 'Fortuner',
        brand: 'Toyota',
        year: 2024,
        description: 'The king of body-on-frame SUVs in India. The Fortuner packs a 2.8L D-4D diesel engine (204 PS, 500 Nm) with 4x4 and a 6-speed automatic. Known for its bulletproof reliability, commanding road presence, and go-anywhere capability. Features include JBL premium audio, cooled seats, wireless charging, and connected car technology. The Fortuner Legender adds sporty styling with a unique front design.',
        images: ['https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?auto=format&fit=crop&w=800&q=80'],
        seats: 7,
        fuelType: 'Diesel',
        transmission: 'Automatic',
        pricePerHour: 350,
        pricePerDay: 3500,
        available: true,
        features: ['AC', '4x4', 'Leather Seats', 'JBL Audio', 'Cooled Seats', 'Wireless Charging', 'Cruise Control'],
        rules: 'No smoking. Premium car — extra ₹5000 damage deposit required. Return with same fuel.',
        rating: 4.9,
        totalBookings: 22,
        category: 'Premium',
    },
    {
        name: 'Innova Crysta',
        brand: 'Toyota',
        year: 2024,
        description: 'India\'s most trusted premium MPV that redefined the segment. Powered by a 2.4L diesel (150 PS) or 2.7L petrol (166 PS). The Crysta seats 7 in executive comfort with captain seats, ambient lighting, rear AC, and a premium cabin. Known for its unmatched reliability, smooth ride, and spacious interior, it\'s the perfect choice for family road trips and airport transfers.',
        images: ['https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80'],
        seats: 7,
        fuelType: 'Diesel',
        transmission: 'Automatic',
        pricePerHour: 280,
        pricePerDay: 2800,
        available: true,
        features: ['AC', 'Captain Seats', 'Touchscreen', 'Ambient Lighting', 'Rear AC', 'Multiple USB Ports'],
        rules: 'No smoking. Perfect for group trips. Return with same fuel level.',
        rating: 4.7,
        totalBookings: 40,
        category: 'Premium',
    },
    {
        name: 'Hector',
        brand: 'MG',
        year: 2024,
        description: 'The Internet Car from MG with a massive 14-inch portrait touchscreen. Available with a 1.5L turbo-petrol (143 PS) or 2.0L diesel (170 PS). Loaded with i-SMART connected car tech powered by Jio, panoramic sunroof, ventilated seats, 360-degree camera, and Infinity premium audio. The Hector\'s bold design with split headlamps and imposing grille makes a strong statement on the road.',
        images: ['https://images.unsplash.com/photo-1617654112368-307921291f42?auto=format&fit=crop&w=800&q=80'],
        seats: 5,
        fuelType: 'Petrol',
        transmission: 'Automatic',
        pricePerHour: 200,
        pricePerDay: 2000,
        available: true,
        features: ['AC', 'Panoramic Sunroof', '14" Touchscreen', 'i-SMART', 'Ventilated Seats', '360 Camera', 'Infinity Audio'],
        rules: 'No smoking. Return with same fuel level. Report any damage immediately.',
        rating: 4.4,
        totalBookings: 25,
        category: 'Premium',
    },
];

const seedDB = async () => {
    try {
        await mongoose.connect(process.env.MONGO_URI);
        console.log('Connected to MongoDB');

        // Clear existing data
        await Car.deleteMany({});
        console.log('Cleared existing cars');

        // Insert all cars
        await Car.insertMany(cars);
        console.log(`✅ Seeded ${cars.length} cars successfully!`);

        // Create admin user if not exists
        const adminExists = await User.findOne({ email: 'admin@carefree.com' });
        if (!adminExists) {
            await User.create({
                name: 'Admin',
                email: 'admin@carefree.com',
                password: 'admin123',
                role: 'admin',
                isVerified: true,
            });
            console.log('✅ Admin user created (admin@carefree.com / admin123)');
        } else {
            console.log('ℹ️  Admin user already exists');
        }

        // Create demo student
        const studentExists = await User.findOne({ email: 'student@cuchd.in' });
        if (!studentExists) {
            await User.create({
                name: 'Suraj Kumar',
                email: 'student@cuchd.in',
                password: 'student123',
                phone: '+91 98765 43210',
                role: 'student',
                universityEmail: 'suraj.kumar@cuchd.in',
                isVerified: true,
            });
            console.log('✅ Demo student created (student@cuchd.in / student123)');
        } else {
            console.log('ℹ️  Demo student already exists');
        }

        console.log('\n🎉 Seeding complete!');
        console.log(`   ${cars.length} cars ready`);
        console.log('   Admin: admin@carefree.com / admin123');
        console.log('   Student: student@cuchd.in / student123');
        process.exit(0);
    } catch (error) {
        console.error('❌ Seeding error:', error.message);
        process.exit(1);
    }
};

seedDB();
